version: '2'
services:
  web:
    build: .
    container_name: nodejs-api
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/code
    links:
      - db
    command: yarn start
  db:
    image: "mongo:3.0.15"
    container_name: mongodb
    ports:
      - "27017:27017"
