version: '2'
services:
  web:
    build: .
    restart: always
    container_name: nodejs-api
    ports: 
      - "3000:3000"
      - "9229:9229"
    volumes: 
      - ./:/code
    links:
      - db
    command: yarn run watch-debug
  db:
    image: "mongo:3.0.15"
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
